pipeline {
        agent {
        dockerfile {
            dir 'Pytest/'
            filename 'Dockerfile'
        }

    }
    stages {
        stage('Run Pytest') {
            steps {
                script {
                    currentBuild.description = "Test: ${params.smoke_test}<br/>Env: ${params.env}<br/>Branch: ${params.branch}"
                }
                script {
                    echo "Running Pytest"

                        logs = sh(script: """
                            cd Pytest \
                            pytest -v \
                                --env=${params.env} \
                                -m "smoke" \
                                --html=Reporting/report.html \
                                --css=Reporting/assets/report.css \
                        """
                }
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
    }
}