pipeline {
        agent {
        dockerfile {
            dir 'Pytest/'
            filename 'Dockerfile'
        }

    }
    stages {
        stage('Example') {
            steps {
                echo 'Hello World'
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
    }
}